// IMPORTANT: This file is auto-generated by `flutterfire configure`.
// Run the following command after setting up your Firebase project:
//
//   flutterfire configure
//
// This will replace this placeholder with the actual configuration.
//
// Prerequisites:
//   1. Create a Firebase project at https://console.firebase.google.com
//   2. Install FlutterFire CLI: dart pub global activate flutterfire_cli
//   3. Run: flutterfire configure
//
// See: https://firebase.google.com/docs/flutter/setup

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtvZUxMpjITlOtLN-GBjrXFL4iTa7T2uQ',
    appId: '1:599287166230:android:085048a2888424a4fd0c37',
    messagingSenderId: '599287166230',
    projectId: 'bytebankapp-3fe6b',
    storageBucket: 'bytebankapp-3fe6b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtvZUxMpjITlOtLN-GBjrXFL4iTa7T2uQ',
    appId: '1:599287166230:android:085048a2888424a4fd0c37',
    messagingSenderId: '599287166230',
    projectId: 'bytebankapp-3fe6b',
    storageBucket: 'bytebankapp-3fe6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyNJS83JXQSKYbX0feEFGb40UNmg1ArSs',
    appId: '1:599287166230:ios:74d879cf7636dafbfd0c37',
    messagingSenderId: '599287166230',
    projectId: 'bytebankapp-3fe6b',
    storageBucket: 'bytebankapp-3fe6b.firebasestorage.app',
    iosBundleId: 'com.grupo30.bytebankapp',
  );
}
